# Generated by Django 5.1.5 on 2025-01-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_category_remove_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
