# Generated by Django 5.1.5 on 2025-01-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_members_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='goods',
            new_name='product',
        ),
    ]
