# Generated by Django 5.1.5 on 2025-01-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_goods_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
