# Generated by Django 5.1.5 on 2025-01-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
