# Generated by Django 5.1.5 on 2025-01-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_category_product_image_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
