# Generated by Django 5.1.5 on 2025-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(max_length=225),
        ),
    ]
